# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161105_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 14, 20, 21, 539430, tzinfo=utc)),
        ),
    ]
